model_configs:
  transformer_best_method2:
    modelname: "Transformer"
    hidden_size: 32
    num_layers: 4
    dropout: 0.2
    method: "method2"
    input_size: 3
    num_classes: 4
    nhead: 8

training_configs:
  default:
    batch_size: 128
    learning_rate: 0.001
